pipeline{
  agent any

  parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }
    
  environment{
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

  stages{
    stage("initial cleanup") {
        steps {
          dir("${WORKSPACE}") {
            deleteDir()
          }
        }
    }

    stage("Checkout SCM") {
      steps{
        git branch: 'main', url: 'https://github.com/MayorFaj/ansible-project.git'
      }
    }

    stage ("Prepare ansible for execution") {
      steps{
        sh 'echo ${WORKSPACE}'
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
      }
    }

    stage ("Run ansible playbook") {
      steps{
        ansiblePlaybook become: true, credentialsId: 'private-key', installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
      }
    }

    stage("clean workspace after build") {
      steps{
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }
  }
}