
---

- name:  webserver role for tooling website
  import_playbook: ../static-assignments/webserver.yml 



- name: import nginx role
  import_playbook: ../static-assignments/nginx.yml


- name: import database file
  import_playbook: ../static-assignments/database.yml