
---

- hosts: tooling
- name:  webserver role for tooling website
  import_playbook: ../static-assignments/webservers.yml 

#- name: import nginx role
#  import_playbook: ../static-assignments/nginx.yml

- hosts: db
- name: import database file
  import_playbook: ../static-assignments/database.yml